Repository 2nd-Layer/rust-cardano-ouroboros-network, pull requests merged in 2020-12, with the labels that each got.

#9 chore: cleaner module structure
  examples/ping.rs
  src/lib.rs
  src/mux.rs
  src/protocols.rs
  src/protocols/chainsync.rs
  src/protocols/chainsync/msg_roll_backward.rs
  src/protocols/chainsync/msg_roll_forward.rs
  src/protocols/handshake.rs
  src/protocols/transaction.rs
Labels: enhancement

#11 Fix(bug): Fix usize wrapping issue
  src/protocols/chainsync.rs
Labels: bug

#14 docs: Add funding information
  .github/FUNDING.yml
  README.md
Labels: documentation

#18 chore: Add licensing header
  examples/ping.rs
  examples/sqlite.rs
  src/lib.rs
Labels: enhancement

#19 ci: Build examples during CI
  .github/workflows/rust.yaml
Labels: enhancement

#15 docs(contributors): Add indidivual contributors UTXO addresses
  README.md
Labels: documentation, enhancement

#22 feat: Add error handling to tcpmux connect() + ping example
  examples/ping.rs
  src/mux/tcp.rs
Labels: enhancement

#25 feat: pass string result/error from miniprotocols
  examples/ping.rs
  src/lib.rs
  src/mux/tcp.rs
  src/protocols/chainsync.rs
  src/protocols/handshake.rs
  src/protocols/transaction.rs
Labels: enhancement

#27 ci: Extend GitHub Actions OS tests
  .github/workflows/rust.yaml
Labels: enhancement

#28 feat(handshake): Improve handshake error handling... actually check the response
  src/mux/tcp.rs
  src/protocols/handshake.rs
Labels: enhancement

#29 fix: Agency issues with TxSubmissionProtocol
  src/lib.rs
  src/mux/tcp.rs
  src/protocols/transaction.rs
Labels: bug

#31 fix: update tcp error handling
  src/mux/tcp.rs
Labels: bug

#33 refactor: add basic support for server role
  examples/server.rs
  examples/sync.rs
  examples/tip.rs
  src/lib.rs
  src/mux/tcp.rs
  src/protocols/chainsync.rs
  src/protocols/handshake.rs
  src/protocols/transaction.rs
Labels: enhancement

#34 refactor: minor fixes, refactoring and examples
  examples/pingpong.rs
  examples/pooltool.rs
  examples/server.rs
  examples/sync.rs
  examples/tip.rs
  src/lib.rs
  src/mux/tcp.rs
  src/protocols.rs
  src/protocols/chainsync.rs
  src/protocols/handshake.rs
  src/protocols/pingpong.rs
  src/protocols/transaction.rs
  src/storage/msg_roll_forward.rs
Labels: enhancement

#35 fix: Allow sync to succeed by skipping byron blocks
  src/protocols/chainsync.rs
  src/storage/msg_roll_backward.rs
Labels: enhancement

#37 docs(readme): Update README.md
  README.md
Labels: documentation

#39 refactor: refactor and remove the storage module
  examples/pooltool.rs
  examples/sqlite.rs
  examples/tip.rs
  src/lib.rs
  src/protocols/chainsync.rs
  src/storage.rs
  src/storage/msg_roll_backward.rs
  src/storage/msg_roll_forward.rs
Labels: enhancement

#41 docs(license): Add SPDX-License-Identifier
  examples/server.rs
  src/protocols/pingpong.rs
Labels: enhancement

#42 fix(release): Release version 0.1.0
  Cargo.toml
Labels: bug

#43 chore(release): Bump-up version to 0.2.0-dev
  Cargo.toml
Labels: documentation, enhancement
