Repository 2nd-Layer/rust-cardano-ouroboros-network, pull requests merged in 2022-01, with the labels that each got.

#84 feat: tokio & handshake improvements
  examples/async.rs
  examples/local.rs
  examples/server.rs
  src/experimental/tokio.rs
  src/mux/connection.rs
  src/protocols/handshake.rs
Labels: enhancement

#88 refactor(ci): Add changelog generation & Improve build workflow
  .github/chglog/RELEASE.tpl.md
  .github/chglog/release.yml
  .github/workflows/rust.yaml
Labels: documentation, enhancement, release

#86 refactor(tokio): big switch to tokio and new internal protocol interface + blockfetch client
  .github/workflows/rust.yaml
  Cargo.toml
  examples/async.rs
  examples/blockfetch.rs
  examples/common.rs
  examples/local.rs
  examples/ping.rs
  examples/pingpong.rs
  examples/server.rs
  examples/sync.rs
  examples/tip.rs
  src/experimental/tokio.rs
  src/lib.rs
  src/mux.rs
  src/protocols.rs
  src/protocols/blockfetch.rs
  src/protocols/chainsync.rs
  src/protocols/handshake.rs
  src/protocols/pingpong.rs
  src/protocols/transaction.rs
  src/protocols/txsubmission.rs
Labels: enhancement, tests/CI

#91 feat(ci): Add automatic update of GH Actions
  .github/dependabot.yml
Labels: enhancement, dependencies

#93 chore(mux): add debug assertions
  src/lib.rs
Labels: enhancement

#94 chore(docs): Update SPDX license headers
  README.md
  examples/blockfetch.rs
  examples/common.rs
  examples/local.rs
  examples/ping.rs
  examples/pooltool.rs
  examples/server.rs
  examples/sqlite.rs
  examples/sync.rs
  examples/tip.rs
  src/mux.rs
  src/mux/connection.rs
  src/protocols.rs
  src/protocols/blockfetch.rs
Labels: documentation, enhancement

#95 ci: Add linting workflow
  .editorconfig
  .github/workflows/check-pr-title.yaml
  .github/workflows/validate.yml
  README.md
  rustfmt.toml
  src/lib.rs
  src/protocols/chainsync.rs
Labels: enhancement, tests/CI
